discourse_subscriptions:
  discourse_subscriptions_enabled:
    default: false
  discourse_subscriptions_extra_nav_subscribe:
    default: false
    client: true
  discourse_subscriptions_pricing_table_id:
    default: ''
    client: true
  discourse_subscriptions_pricing_table_enabled:
    default: false
    client: true
  discourse_subscriptions_public_key:
    default: ''
    client: true
  discourse_subscriptions_secret_key:
    default: ''
    client: false
  discourse_subscriptions_webhook_secret:
    default: ''
    client: false
  discourse_subscriptions_currency:
    client: true
    default: "INR"
    type: enum
    choices:
      - AUD
      - BRL
      - CAD
      - EUR
      - GBP
      - INR
      - NZD
      - USD
      - DKK
      - SGD
      - ZAR
      - CHF
      - PLN
      - CZK
  discourse_subscriptions_enable_automatic_tax:
    default: false
  discourse_subscriptions_enable_verbose_logging:
    default: false
  discourse_subscriptions_payment_provider:
    default: "Stripe"
    type: enum
    choices:
      - Stripe
      - Razorpay
    client: true
  discourse_subscriptions_razorpay_key_id:
    default: ""
    client: true

  discourse_subscriptions_razorpay_key_secret:
    default: ""
    client: false

  discourse_subscriptions_razorpay_webhook_secret:
    default: ""
    client: false
